SELECT 	  REL.COD_PROCESO_TIPO
		, PRO.PROCESO_TIPO
        , REL.COD_PERSONA_CONDICION
        , PER.PERSONA_CONDICION
        , REL.COD_DETALLE_TIPO
        , DET.DETALLE_TIPO
        , REL.ORDEN
        , REL.OBSERVACIONES
FROM 	  rel_pers_cond_proc_tipo_deta_tipo AS REL
		, ref_detalle_tipo AS DET
        , ref_persona_condicion AS PER
        , ref_proceso_tipo AS PRO
WHERE REL.COD_PERSONA_CONDICION = PER.COD_PERSONA_CONDICION
  AND REL.COD_PROCESO_TIPO = PRO.COD_PROCESO_TIPO
  AND REL.COD_DETALLE_TIPO = DET.COD_DETALLE_TIPO
  AND (REL.COD_PROCESO_TIPO = 2 OR REL.COD_PROCESO_TIPO = 3 OR REL.COD_PROCESO_TIPO = 4)
  AND (REL.COD_PERSONA_CONDICION = 2 OR REL.COD_PERSONA_CONDICION = 3 OR REL.COD_PERSONA_CONDICION = 4)