INSERT INTO `sise_legal`.`bsd_usuario` (`cod_usuario`,`usuario`, `password`, `nombre`, `apellido`, `correo_electronico`, `cod_rol`) VALUES (1, 'Admin', '123', 'SISE', 'Servicios', 'info@siseservicios.com', '1');
INSERT INTO `sise_legal`.`bsd_usuario` (`cod_usuario`,`usuario`, `password`, `nombre`, `apellido`, `correo_electronico`, `cod_rol`) VALUES (2, 'FMARTINO', 'FMARTINO.2017', 'Fernando Agustín', 'Martino', 'sebatista385@gmail.com', '1');
INSERT INTO `sise_legal`.`bsd_usuario` (`cod_usuario`,`usuario`, `password`, `nombre`, `apellido`, `correo_electronico`, `cod_rol`) VALUES (3, 'IBAZO', 'IBAZO.123', 'Inés', 'Bazo', 'sebatista385@gmail.com', '3');
INSERT INTO `sise_legal`.`bsd_usuario` (`cod_usuario`,`usuario`, `password`, `nombre`, `apellido`, `correo_electronico`, `cod_rol`) VALUES (4, 'AGRECO', 'AGRECO.123', 'Adriel', 'Greco', 'sebatista385@gmail.com', '3');
INSERT INTO `sise_legal`.`bsd_usuario` (`cod_usuario`,`usuario`, `password`, `nombre`, `apellido`, `correo_electronico`, `cod_rol`) VALUES (5, 'MOTERO', 'MOTERO.123', 'Matías', 'Otero', 'sebatista385@gmail.com', '3');
INSERT INTO `sise_legal`.`bsd_usuario` (`cod_usuario`,`usuario`, `password`, `nombre`, `apellido`, `correo_electronico`, `cod_rol`) VALUES (6, 'SPERELLI', 'SPERELLI.123', 'Sofía', 'Perelli', 'sebatista385@gmail.com', '3');
INSERT INTO `sise_legal`.`bsd_usuario` (`cod_usuario`,`usuario`, `password`, `nombre`, `apellido`, `correo_electronico`, `cod_rol`) VALUES (7, 'MROSAS', 'MROSAS.123', 'Mariano', 'Rosas', 'sebatista385@gmail.com', '3');
INSERT INTO `sise_legal`.`bsd_usuario` (`cod_usuario`,`usuario`, `password`, `nombre`, `apellido`, `correo_electronico`, `cod_rol`) VALUES (8, 'EDIAZ', 'EDIAZ.123', 'Emiliano', 'Diaz', 'sebatista385@gmail.com', '3');
INSERT INTO `sise_legal`.`bsd_usuario` (`cod_usuario`,`usuario`, `password`, `nombre`, `apellido`, `correo_electronico`, `cod_rol`) VALUES (9, 'VDOVAL', 'VDOVAL.123', 'Victoria', 'Doval', 'sebatista385@gmail.com', '3');
