#Accidente de tránsito - Cliente
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2',  '2', '020020', 'Accidente de tránsito - Cliente - ¿Titular dominial del vehiculo?', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2',  '3', '020030', 'Accidente de tránsito - Cliente - ¿Habían acompañantes en el vehículo?', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2',  '4', '020040', 'Accidente de tránsito - Cliente - ¿Cuantos acompañantes había en el vehículo?', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2',  '5', '020050', 'Accidente de tránsito - Cliente - ¿Que cobertura dispone?', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2',  '9', '020090', 'Accidente de tránsito - Cliente - Relato de los hechos', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '10', '020100', 'Accidente de tránsito - Cliente - Fecha y hora de los hechos', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '11', '020110', 'Accidente de tránsito - Cliente - Dirección, altura y sentido', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '12', '020120', 'Accidente de tránsito - Cliente - Descripción de Lesiones', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '13', '020130', 'Accidente de tránsito - Cliente - Lugares de atención de lesiones', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '14', '020140', 'Accidente de tránsito - Cliente - Datos adicionales de interes', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '41', '020410', 'Accidente de tránsito - Cliente - Copia del DNI', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '42', '020420', 'Accidente de tránsito - Cliente - Copia de Registro de conducir', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '43', '020430', 'Accidente de tránsito - Cliente - Copia de denuncia administrativa (72 hs del s', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '44', '020440', 'Accidente de tránsito - Cliente - Constancia de atención en hospital (Día del s', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '45', '020450', 'Accidente de tránsito - Cliente - Copia de la historia clínica', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '46', '020460', 'Accidente de tránsito - Cliente - Copia de Estudios médicos realizados', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '47', '020470', 'Accidente de tránsito - Cliente - Presupuesto', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '48', '020480', 'Accidente de tránsito - Cliente - Copia de Cedula Verde', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '49', '020490', 'Accidente de tránsito - Cliente - Copia de la constancia de cobertura', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '50', '020500', 'Accidente de tránsito - Cliente - Fotos color de los daños', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '51', '020510', 'Accidente de tránsito - Cliente - Fotos color de los daños con patente visible', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '57', '020570', 'Accidente de tránsito - Cliente - Pedir informe de dominio', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '58', '020580', 'Accidente de tránsito - Cliente - Documentación pendiente', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '59', '020590', 'Accidente de tránsito - Cliente - Pedir mediacióm', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '60', '020600', 'Accidente de tránsito - Cliente - Vista médica', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '61', '020610', 'Accidente de tránsito - Cliente - Lugar de Vista médica', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '62', '020620', 'Accidente de tránsito - Cliente - Fecha de Vista médica', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '63', '020630', 'Accidente de tránsito - Cliente - Hora de Vista médica', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '64', '020640', 'Accidente de tránsito - Cliente - En negociación', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '65', '020650', 'Accidente de tránsito - Cliente - Para armar demanda', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '2', '66', '020660', 'Accidente de tránsito - Cliente - Para cobrar', '1', SYSDATE());

#Accidente de tránsito - Oponente
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('3', '2',  '6', '030060', 'Accidente de tránsito - Oponente - Compañia de seguro', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('3', '2',  '7', '030070', 'Accidente de tránsito - Oponente - Nro. de Poliza', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('3', '2',  '8', '030080', 'Accidente de tránsito - Oponente - Nro. de siniestro', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('3', '2', '52', '030520', 'Accidente de tránsito - Oponente - Estudio Jurídico', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('3', '2', '53', '030530', 'Accidente de tránsito - Oponente - Abogado de Estudio Jurídico', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('3', '2', '54', '030540', 'Accidente de tránsito - Oponente - Teléfono de Estudio Jurídico', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('3', '2', '55', '030550', 'Accidente de tránsito - Oponente - Correo electrónico de Estudio Jurídico', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('3', '2', '56', '030560', 'Accidente de tránsito - Oponente - Domicilio de Estudio Jurídico', '1', SYSDATE());

#Accidente de tránsito - Empleador

#Accidente laboral - Cliente
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '15', '020150', 'Accidente laboral - Cliente - Fecha de ingreso a la relación laboral', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '16', '020160', 'Accidente laboral - Cliente - Actividad relizada', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '17', '020170', 'Accidente laboral - Cliente - Jornada Laboral', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '19', '020190', 'Accidente laboral - Cliente - Mejor remuneración', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '20', '020200', 'Accidente laboral - Cliente - Lugar de prestación de tareas', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '27', '020270', 'Accidente laboral - Cliente - Categoria laboral', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '28', '020280', 'Accidente laboral - Cliente - C.C.T. Aplicable', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '29', '020290', 'Accidente laboral - Cliente - ¿Que ART posee?', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '30', '020300', 'Accidente laboral - Cliente - Día del accidente', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '31', '020310', 'Accidente laboral - Cliente - Lugar del accidente', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '32', '020320', 'Accidente laboral - Cliente - Zona lesionada', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '33', '020330', 'Accidente laboral - Cliente - Nombre de la lesión', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '34', '020340', 'Accidente laboral - Cliente - Mecánica del hecho', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '35', '020350', 'Accidente laboral - Cliente - ¿La ART dió prestaciones médicas?', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '36', '020360', 'Accidente laboral - Cliente - Comentarios de prestaciones médicas de ART', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '37', '020370', 'Accidente laboral - Cliente - ¿Posee alta laboral?', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '38', '020380', 'Accidente laboral - Cliente - Comentarios sobre alta laboral', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '39', '020390', 'Accidente laboral - Cliente - Lugar de atención médica ART', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '40', '020400', 'Accidente laboral - Cliente - Lugar de atención médica particular', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '58', '020580', 'Accidente laboral - Cliente - Documentación pendiente', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '59', '020590', 'Accidente laboral - Cliente - Pedir mediación', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '60', '020600', 'Accidente laboral - Cliente - Vista médica', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '61', '020610', 'Accidente laboral - Cliente - Lugar de Vista médica', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '62', '020620', 'Accidente laboral - Cliente - Fecha de Vista médica', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '63', '020630', 'Accidente laboral - Cliente - Hora de Vista médica', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '64', '020640', 'Accidente laboral - Cliente - En negociación', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '65', '020650', 'Accidente laboral - Cliente - Para armar demanda', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '66', '020660', 'Accidente laboral - Cliente - Para cobrar', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '3', '67', '020345', 'Accidente laboral - Cliente - Lugar de primer atención médica', '1', SYSDATE());

#Accidente laboral - Oponente
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('3', '3', '52', '520', 'Accidente laboral - Oponente - Estudio Jurídico', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('3', '3', '53', '530', 'Accidente laboral - Oponente - Abogado de Estudio Jurídico', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('3', '3', '54', '540', 'Accidente laboral - Oponente - Teléfono de Estudio Jurídico', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('3', '3', '55', '550', 'Accidente laboral - Oponente - Correo electrónico de Estudio Jurídico', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('3', '3', '56', '560', 'Accidente laboral - Oponente - Domicilio de Estudio Jurídico', '1', SYSDATE());

#Accidente laboral - Empleador

#Despido laboral - Cliente
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '15', '150', 'Despido laboral - Cliente - Fecha de ingreso a la relación laboral', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '16', '160', 'Despido laboral - Cliente - Actividad relizada', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '17', '170', 'Despido laboral - Cliente - Jornada Laboral', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '19', '190', 'Despido laboral - Cliente - Mejor remuneración', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '20', '200', 'Despido laboral - Cliente - Lugar de prestación de tareas', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '21', '210', 'Despido laboral - Cliente - ¿Hay registración deficiente?', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '22', '220', 'Despido laboral - Cliente - ¿Cual es la registración deficiente?', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '23', '230', 'Despido laboral - Cliente - ¿Realizaba horas extras?', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '24', '240', 'Despido laboral - Cliente - Comentarios de horas extras', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '25', '250', 'Despido laboral - Cliente - ¿Hay salarios adeudados?', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '26', '260', 'Despido laboral - Cliente - Comentarios de salarios adeudados', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '27', '270', 'Despido laboral - Cliente - Categoria laboral', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '28', '280', 'Despido laboral - Cliente - C.C.T. Aplicable', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '57', '570', 'Despido laboral - Cliente - Informe de dominio', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '58', '580', 'Despido laboral - Cliente - Documentación pendiente', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '59', '590', 'Despido laboral - Cliente - Pedir mediación', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '64', '640', 'Despido laboral - Cliente - En negociación', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '65', '650', 'Despido laboral - Cliente - Para armar demanda', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('2', '4', '66', '660', 'Despido laboral - Cliente - Para cobrar', '1', SYSDATE());

#Despido laboral - Oponente

#Despido laboral - Empleador
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('4', '4', '52', '520', 'Despido laboral - Empleador - Estudio Jurídico', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('4', '4', '53', '530', 'Despido laboral - Empleador - Abogado de Estudio Jurídico', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('4', '4', '54', '540', 'Despido laboral - Empleador - Teléfono de Estudio Jurídico', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('4', '4', '55', '550', 'Despido laboral - Empleador - Correo electrónico de Estudio Jurídico', '1', SYSDATE());
INSERT INTO `sise_legal`.`rel_pers_cond_proc_tipo_deta_tipo` (`cod_persona_condicion`, `cod_proceso_tipo`, `cod_detalle_tipo`, `orden`, `observaciones`, `usr_ult_modif`, `fec_ult_modif`) VALUES ('4', '4', '56', '560', 'Despido laboral - Empleador - Domicilio de Estudio Jurídico', '1', SYSDATE());
